packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@suites/di.nestjs'
  - '@suites/doubles.jest'
  - '@swc/core'
  - prisma
  - unrs-resolver
  - esbuild
